# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for STR
   pod 'SVProgressHUD'
   pod 'IQKeyboardManagerSwift'
   pod 'ReachabilitySwift'
   pod 'Codextended'
   pod 'AWSS3'
   pod 'SDWebImage'
   pod 'Alamofire', '~> 4.8.2'
   
   source 'https://github.com/CocoaPods/Specs.git'
   pod 'AWSAppSync'
   pod 'AWSMobileClient'
   pod 'SwiftyDropbox'
   
  target 'STRTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'STRUITests' do
    # Pods for testing
  end

end
